// Generated by CoffeeScript 1.3.1
(function() {
  var $, SIZE_BUTTONS, highlight_big_folders, toggle_label;

  $ = jQuery;

  SIZE_BUTTONS = {
    btn1mb: /[0-9][0-9]*M|.*G/,
    btn10mb: /[0-9][0-9][0-9]*M|.*G/,
    btn100mb: /[0-9][0-9][0-9]M|.*G/,
    btn1gb: /[0-9][0-9]*G/,
    btn10gb: /[0-9][0-9][0-9]*G/,
    btn100gb: /[0-9][0-9][0-9]G/
  };

  $(function() {
    $('#size-buttons button').click(function() {
      return highlight_big_folders(SIZE_BUTTONS[$(this).attr('id')]);
    });
    $('.filebrowser button.enabled').click(function() {
      var subfolder;
      subfolder = $(this).parent().next("div");
      subfolder.toggle();
      toggle_label($(this));
      return highlight_big_folders(SIZE_BUTTONS[$('#size-buttons .btn.active').attr('id')], subfolder);
    });
    $('#folders > .folder > button').click();
    highlight_big_folders(SIZE_BUTTONS['btn1gb']);
    return $('#loading').hide();
  });

  toggle_label = function(element) {
    element.children(":first").toggleClass('icon-folder-open');
    return element.children(":first").toggleClass('icon-folder-close');
  };

  highlight_big_folders = function(size_regex, parent_el) {
    var num_highlighted;
    if (parent_el == null) {
      parent_el = $('#folders');
    }
    num_highlighted = 0;
    return parent_el.find("div.folder:visible .size").each(function() {
      var size;
      size = $(this).text();
      if (size_regex.test(size)) {
        return $(this).prev('button').addClass('btn-danger');
      } else {
        return $(this).prev('button').removeClass('btn-danger');
      }
    });
  };

}).call(this);
